### PR TITLE
use dev and preview instead of start

### PR DESCRIPTION
**Pull request by JeelRajodiya**
If this PR gets accepted then i will also update the nano-react-app/template-ts and  readme file of nano-react-app/nano-react-app

### CODE REVIEW

**Comment by adrianmcli** [comment]
lgtm, thanks a lot! happy to accept the other PR too

**Comment by mgreasly** [comment]
Hey - just on this; any reason to remove start? happy to have additional options for run, but personally I prefer the shorthand 'npm start' rather than 'npm run dev'? We can have both options available ('npm start' is just a convenient shorthand for 'npm run start' after all).

**Comment by adrianmcli** [comment]
good point @mgreasly, I apologize as I took a quick look at the diff and overlooked this.

@JeelRajodiya any thoughts?

**Comment by JeelRajodiya** [comment]
> good point @mgreasly, I apologize as I took a quick look at the diff and overlooked this.
> 
> @JeelRajodiya any thoughts?

@mgreasly  got a point! npm start is s a good shorthand. how about setting both "npm run dev "and "npm start"for development server?

**Comment by adrianmcli** [comment]
@JeelRajodiya I will say that I prefer to leave it as `npm start` as that is the industry convention for getting a project running ASAP. I'm not sure that we want two scripts that do the same thing. Keep in mind that this is just a template. People can always change the `package.json` to suit their needs.

**Comment by JeelRajodiya** [comment]
> @JeelRajodiya I will say that I prefer to leave it as `npm start` as that is the industry convention for getting a project running ASAP. I'm not sure that we want two scripts that do the same thing. Keep in mind that this is just a template. People can always change the `package.json` to suit their needs.

yes, two scripts that does the same job is bad practice. we should just go with the industry convention.

**Pull request merged**
